### ISSUE TITLE
Authentication doesn't work on (private) GitLab and GitHub anymore

### ISSUE THREAD

**Issue by Frank-G** [kns-it/Docker-GitPitch#11]
Dear all,

first of all, thanks for providing this container for GitPitch. Unfortunately, since the beginning of January the authentication doesn't work anymore on my private GitLab installation (11.7). It also doesn't work on GitHub anymore. So, GitPitch can't access private repositories anymore. I use a Token with full access. 

Are you aware of such an issue?

I also tried to rebuild the container, but still no success. 

Best regards,
Frank

**Comment by prskr** [comment]
Hi Frank,

unfortunately private access is actually a pro feature.
I haven't tried private access in the open source GitPitch edition for a while so I was not aware that the feature is not working anymore.

Without any investigation of your actual problem: did you check if your configuration is set to access GitLab API V4? V3 got disabled with GitLab 11.0.
If that's not working changes of the GitPitch code might be required but I'm afraid that I won't have time to investigate the problem in the upcoming weeks.

**Comment by Frank-G** [comment]
Thanks for your time.

I set the API URL to /v4, so I assume it was always using v4. It was working flawlessly for me before. But if you say the open source version should have never worked for private repositories, I guess the repository was public before that point...

**Comment by prskr** [comment]
It's not that the OS version was not really working but it was never completely functional because static assets like CSS or images where referenced directly to the repository tree and therefore couldn't be loaded by the browser if you weren't logged in already and if you didn't have sufficient privileges to access those assets.

I'm sorry that there are apparently even more problems with the OS version in combination with private repositories than before but I'm afraid I can't help you with this issue.

I'll close the issue for now.

**Comment by Frank-G** [comment]
Sure, thanks a lot for your help!
